Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/20240722092641_devise_create_users.rb'
    - 'db/migrate/20240722101446_create_active_storage_tables.active_storage.rb'
    - 'db/migrate/20240813081229_create_matches.rb'
    - 'db/migrate/20240806070317_create_stadia.rb'
    - 'app/models/ability.rb'
    - 'app/controllers/seasons_controller.rb'
    - 'app/controllers/matches_controller.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/20240722101446_create_active_storage_tables.active_storage.rb'
    - 'app/models/ability.rb'
    - 'app/controllers/seasons_controller.rb'
    - 'app/controllers/matches_controller.rb'
    - 'app/controllers/match_videos_controller.rb'
    - 'app/controllers/fan_matches_controller.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'
    - 'config/routes.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/requests/fan_matches_spec.rb'
    - 'spec/requests/match_videos_spec.rb'
    - 'spec/requests/matches_spec.rb'
    - 'spec/requests/seasons_spec.rb'